version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true
build_script:
- dotnet build NetDotEnv.sln -c Release -v q /nologo
- dotnet pack src/NetDotEnv/NetDotEnv.csproj -c Release -o .\artifacts --include-symbols --no-build
test_script:
- dotnet test test/NetDotEnv.Test/NetDotEnv.Test.csproj --configuration Release  --no-build

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: yDEnVsrOvcaHOWO0+C75GhSUZmb8LyB8a7vxqXAYcpdJpedEpK66SkubLhsBpc6n
  on:
    appveyor_repo_tag: true